name: CI
on: [push, pull_request]
jobs:
  build-engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build engine
        run: |
          sudo apt-get update && sudo apt-get install -y cmake g++
          cmake -S engine -B engine/build
          cmake --build engine/build -j
  server-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r server/requirements.txt
      - run: python -c "import fastapi; print('FastAPI OK')"
